import "../styles/globals.css";
import "../styles/components.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="es" className={`${geistSans.variable} ${geistMono.variable} ${stackSans.variable}`}>
      <body>{children}</body>
    </html>
  );
}
